name = "tradeledger-server"
main = "worker.js"
compatibility_date = "2026-04-19"
compatibility_flags = ["nodejs_compat"]

[[kv_namespaces]]
binding = "TRADELEDGER_KV"
id = "7f3cb6ec41b14a39b85ac16c4bc41cd9"

[vars]
TRADELEDGER_TOKEN = "TL-S7PDZ3UV"
